services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goexperts
      MYSQL_PASSWORD: root
    volumes:
      - ./data:/data # Corrigido
    ports:
      - 3306:3306